# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='enddate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
