# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_authorization_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='authorizationid',
            field=models.CharField(default=45484845, max_length=11),
            preserve_default=False,
        ),
    ]
